"""init

Revision ID: 481463213831
Revises: 
Create Date: 2026-08-28 23:01:45.002769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '481463213831'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('delivery_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_by_id', sa.String(length=36), nullable=False),
    sa.Column('customer_name', sa.String(length=100), nullable=False),
    sa.Column('customer_phone', sa.String(length=20), nullable=False),
    sa.Column('delivery_address', sa.String(length=255), nullable=False),
    sa.Column('item_description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('assigned_rider_id', sa.String(length=36), nullable=True),
    sa.Column('qr_token', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_rider_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('qr_token')
    )
    op.create_table('delivery_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('delivery_request_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['delivery_request_id'], ['delivery_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proof_of_deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('delivery_request_id', sa.String(length=36), nullable=False),
    sa.Column('scan_type', sa.String(length=20), nullable=False),
    sa.Column('scanned_by_id', sa.String(length=36), nullable=False),
    sa.Column('scanned_at', sa.DateTime(), nullable=True),
    sa.Column('token_used', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['delivery_request_id'], ['delivery_requests.id'], ),
    sa.ForeignKeyConstraint(['scanned_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('proof_of_deliveries')
    op.drop_table('delivery_events')
    op.drop_table('delivery_requests')
    op.drop_table('users')
    # ### end Alembic commands ###
